unique_ids:
  forms: {Form1: W7DQUKNWZDKW3BOQZMF5GRFVGYX5HQCL}
  modules: {}
  server_modules: {ServerModule1: T6SRVWBNMTUK7NJZXEUYBVUKKKSOVX66}
  assets: {standard-page.html: ZPYYRCQET3OYWSLC6IMPXGJ2ZF44XFAV, theme.css: H4KNQ3Q5OQ4SRQZORX5JMXKS6INP4BXV}
