unique_ids:
  forms: {ArticleEdit: M7RHWKUWS4HXXT7M5YE3HXHIWWLHRQBL, ArticleView: QEKKTD6ERQPSVR4LAWSZLORA66NFW3JD,
    Homepage: O6LGLL7TOBT4NPDLDEBGQXBO6MUMGCMJ}
  modules: {}
  server_modules: {ServerModule1: H6HMMJ4TTLYNQXALQJJUJUGIISIAVONA}
  assets: {standard-page.html: U7URNLH57OWOTH5QEKYE3LD2567WIBAS, theme.css: U5NBJIVAFRYGZPL4TMMZZOZCWR7LGTRZ}
